# This workflow will build a container and deploy it to an Azure Functions App on Linux when a commit is pushed to your default branch.
#
name: Prod Deployment by Docker 

on:
  push:
    branches: ["prod"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4
      
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: 'svcbavideoacr.azurecr.io'
        username: ${{ secrets.AZURE_USERNAME }}
        password: ${{ secrets.AZURE_PWD }}

    - name: Build and Push Docker Image
      run: |
        docker build --build-arg ENVIRONMENT=production -t svcbavideoacr.azurecr.io/svcsa-next-prod:latest .
        docker push svcbavideoacr.azurecr.io/svcsa-next-prod:latest
        
    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
        dns-name-label: 'prod-svcsa-web'
        image: 'svcbavideoacr.azurecr.io/svcsa-next-prod:latest'
        registry-login-server: 'svcbavideoacr.azurecr.io'
        registry-username: ${{ secrets.AZURE_USERNAME }}
        registry-password: ${{ secrets.AZURE_PWD }}
        name: 'svcsa-web-prod-container'
        ports: 3000
        location: 'west us'
        
    - name: Azure logout
      run: |
        az logout
